name: DevOps Project

on:
  push:
    branches: 
      - 'main'

jobs:
  build-and-push:
    name: Build Docker image and push to GitHub Docker Registry
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/devopsproject/my-demo-app:latest .

      - name: Push Docker Image
        run: |
          docker push ghcr.io/devopsproject/my-demo-app:latest